[package]
name = "rust_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Cargo.toml
[build-dependencies]
bindgen = "0.59.1" 

[dependencies]
libc = "0.2"